"""Centralized icon name constants — typo-safe references to lucide icons."""
from __future__ import annotations

SEARCH = "search"
REFRESH = "refresh-cw"
DOWNLOAD = "download"
TRASH = "trash-2"
EXTERNAL_LINK = "external-link"
CHECK = "check"
X = "x"
CHEVRON_DOWN = "chevron-down"
CHEVRON_LEFT = "chevron-left"
CHEVRON_RIGHT = "chevron-right"
ARROW_UP_DOWN = "arrow-up-down"
INFO = "info"
ALERT = "triangle-alert"
COPY = "copy"
FILTER = "list-filter"
BOOK_OPEN = "book-open"
LAYERS = "layers"
PLAY = "play"
